# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build App IPA"
  lane :build_ipa_to_testflight do
    build_app(
        scheme: "Runner",
        workspace: "Runner.xcworkspace",
        output_directory: "../build/ios/ipa",
        output_name: "Runner.ipa"
    )
    api_key = app_store_connect_api_key(
        key_id: File.read("../_local/AuthKeyId.txt"),
        issuer_id: File.read("../_local/IssuerId.txt"),
        key_filepath: "_local/AuthKey.p8",
    )
    upload_to_testflight(
        api_key: api_key,
        ipa: "../build/ios/ipa/Runner.ipa"
    )
    # add actions here: https://docs.fastlane.tools/actions
  end
end
